# Copyright © 2021 William L Horvath II
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM identifier_api

ARG guid
ARG uuid
ARG identifier_data_path
ARG flask_env
ARG build_id
ARG cert_subj

ENV IDENTIFIER_DATA_PATH=$identifier_data_path
ENV BUILD_ID=$build_id
ENV FLASK_ENV=$flask_env
ENV VIRTUAL_ENV=.venv
ENV ROOT_LOG_LEVEL=DEBUG

RUN openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout /etc/ssl/private/identifier.key \
        -out /etc/ssl/certs/identifier.crt \
        -subj $cert_subj

WORKDIR /service/identifier
COPY . /service/identifier
COPY nginx.conf /etc/nginx/nginx.conf
COPY supervisord.conf /etc/supervisord.conf

RUN python -m venv $VIRTUAL_ENV \
    && $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
    && $VIRTUAL_ENV/bin/pip install setuptools \
    && $VIRTUAL_ENV/bin/pip install build \
    && $VIRTUAL_ENV/bin/python -m build --wheel -o ./ \
    && $VIRTUAL_ENV/bin/pip install ./*.whl

ENV PATH=$PATH:$VIRTUAL_ENV/bin

EXPOSE 443
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/service/identifier/supervisord.conf"]
