version: "3.9"

services:
  api:
    env_file:
      - .env
    build:
      context: .
      args:
        - guid=${IGID}
        - uuid=${IUID}
        - identifier_data_path=${IDENTIFIER_DATA_PATH}
        - identifier_log_level=${IDENTIFIER_LOG_LEVEL}
        - identifier_max_reader_count=${IDENTIFIER_MAX_READER_COUNT}
        - identifier_max_retries=${IDENTIFIER_MAX_RETRIES}
        - flask_env=${FLASK_ENV}
        - build_id=${BUILD_ID}
        - cert_subj=${CERT_SUBJ}
    ports:
      - "4430:443"
    container_name: identifier_api
    volumes:
      - ${LOCAL_DATA_PATH}:${IDENTIFIER_DATA_PATH}
