[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --capture=tee-sys --log-level=DEBUG --rootdir=./src/tests"
testpaths = [
    "src/tests",
]


[build-system]
requires = ["setuptools", "wheel", "build"]
build-backend = "setuptools.build_meta"
